name: Symbol updater
permissions: read-all
on:
  workflow_dispatch:
  schedule:
    - cron: "20 */5 * * *"

jobs:
  run:
    runs-on: ubuntu-24.04
    name: PHP ${{ matrix.php-version }} - Dump
    strategy:
      matrix:
        php-version:
          - '5.3'
          - '5.4'
          - '5.5'
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        if: matrix.php-version != '8.5' && matrix.php-version != '8.4' # Instead of using setup-php, compile PHP from source instead.
        with:
          php-version: ${{ matrix.php-version }}
        env:
          update: true

      - name: Compile and Setup PHP (${{ matrix.php-version }})
        uses: PHPWatch/compile-php@main
        if: matrix.php-version == '8.5' || matrix.php-version == '8.4'
        with:
          branch: ${{ matrix.php-version == '8.5' && 'master' || 'PHP-8.4' }}
        env:
          update: true

      - name: Display versions and env
        run: |
          php -v
          php -m
          
      - name: "Install Composer dependencies"
        run:
          composer dump-autoload

      - name: Dump data
        run: |
          php bin/dump.php

      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.php-version }}
          path: scratch

  collect:
    needs: run
    runs-on: ubuntu-latest
    name: Collect and Commit Data
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout main repo

      - uses: actions/checkout@v4
        name: Checkout data repo
        with:
          repository: PHPWatch/PHP-Symbols
          path: data
          token: ${{ secrets.DATA_REPO_PAT }}

      - name: Collect data
        uses: actions/download-artifact@v4
        with:
          path: scratch

      - name: Prime files
        run: |
          cp -Rf data/.git data-repo-meta
          cp data/README.md data-README.md
          rm data -Rf
          mkdir data
          mv data-repo-meta data/.git 
          mv data-README.md data/README.md 
          cp scratch/* data/ -Rf

      - name: List dirs
        run: find data | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Generate commit message
        id: commit_msg
        run: echo "commit_msg=$(date +"%Y %b %d")" >> "$GITHUB_OUTPUT"

      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.commit_msg.outputs.commit_msg }}
          branch: main
          repository: data
          add_options: '-A'
