name: Symbol updater
permissions: read-all
on:
  workflow_dispatch:
  schedule:
    - cron: "20 */12 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-version }} - Dump
    strategy:
      matrix:
        php-version:
          - version: '5.3'
            extensions: none, bcmath, bz2, calendar, com_dotnet, Core, ctype, curl, date, dba, dom, enchant, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, interbase, intl, json, ldap, libxml, mbstring, mcrypt, mysql, mysqli, mysqlnd, oci8, odbc, openssl, pcntl, pcre, PDO, pdo_dblib, pdo_firebird, pdo_mysql, PDO_oci, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, Reflection, session, shmop, SimpleXML, snmp, soap, sockets, SPL, SQLite, sqlite3, standard, sybase_ct, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib, opcache
          - version: '5.4'
            extensions: ''
          - version: '5.5'
            extensions: ''
          - version: '5.6'
            extensions: ''
          - version: '7.0'
            extensions: ''
          - version: '7.1'
            extensions: ''
          - version: '7.2'
            extensions: ''
          - version: '7.3'
            extensions: ''
          - version: '7.4'
            extensions: ''
          - version: '8.0'
            extensions: ''
          - version: '8.1'
            extensions: ''
          - version: '8.2'
            extensions: ''
          - version: '8.3'
            extensions: ''
          - version: '8.4' # Compile
            extensions: '' # Not relevant
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        if: matrix.php-version != '8.4' # Instead of using setup-php, compile PHP from source instead.
        with:
          php-version: ${{ matrix.php-version.version }}
          extensions: ${{ matrix.php-version.extensions }}
        env:
          update: true

      - name: Compile and Setup PHP
        uses: PHPWatch/compile-php@main
        if: matrix.php-version == '8.4' # PHP 8.4 is the current `master` branch.

      - name: Display versions and env
        run: |
          php -v
          php -m
          
      - name: "Install Composer dependencies"
        run:
          composer dump-autoload

      - name: Dump data
        run: |
          php bin/dump.php

      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.php-version }}
          path: scratch

  collect:
    needs: run
    runs-on: ubuntu-latest
    name: Collect and Commit Data
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout main repo

      - uses: actions/checkout@v4
        name: Checkout data repo
        with:
          repository: PHPWatch/PHP-Symbols
          path: data
          token: ${{ secrets.DATA_REPO_PAT }}

      - name: Collect data
        uses: actions/download-artifact@v4
        with:
          path: scratch

      - name: Prime files
        run: |
          cp scratch/* data/ -Rf

      - name: List dirs
        run: find data | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Generate commit message
        id: commit_msg
        run: echo "commit_msg=$(date +"%Y %b %d")" >> "$GITHUB_OUTPUT"

      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.commit_msg.outputs.commit_msg }}
          branch: main
          repository: data
          add_options: '-A'
